# Generated by Django 4.2.11 on 2024-05-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMP_ID", models.CharField(max_length=1000)),
                ("EMP_NAME", models.CharField(max_length=1000)),
                ("EMP_COMP_ID", models.CharField(max_length=1000)),
                ("EMP_MAILID", models.CharField(max_length=1000)),
                ("EMP_PHONENO", models.CharField(max_length=1000)),
                ("EMP_DOJ", models.CharField(max_length=1000)),
                ("EMP_ROLE_NAME", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="VisitorDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VS_ID", models.CharField(max_length=1000)),
                ("VS_NAME", models.CharField(max_length=1000)),
                ("VS_DATE", models.CharField(max_length=1000)),
                ("VS_PHONENO", models.CharField(max_length=1000)),
                ("VS_EMAILID", models.CharField(max_length=1000)),
                ("VS_PURPOSE", models.CharField(max_length=1000)),
                ("VS_REMARKS", models.CharField(max_length=1000)),
            ],
        ),
    ]
