# Generated by Django 4.2.11 on 2024-06-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitordetails", old_name="VS_EMAILID", new_name="VS_MAILID",
        ),
    ]
