# Generated by Django 4.2.11 on 2024-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0002_rename_vs_emailid_visitordetails_vs_mailid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VS_ID", models.CharField(max_length=1000, unique=True)),
                ("VS_NAME", models.CharField(max_length=1000)),
                ("VS_DATE", models.DateField()),
                ("VS_PHONENO", models.CharField(max_length=15)),
                ("VS_MAILID", models.EmailField(max_length=254)),
                ("VS_PURPOSE", models.TextField()),
                ("VS_REMARKS", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=50)),
            ],
        ),
    ]
