# Generated by Django 4.2.11 on 2024-06-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0003_visitor"),
    ]

    operations = [
        migrations.DeleteModel(name="Visitor",),
    ]
