# Generated by Django 4.2.11 on 2024-06-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0004_delete_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitordetails",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
