# Generated by Django 4.2.11 on 2024-06-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0005_visitordetails_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeedetails",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_COMP_ID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employeedetails", name="EMP_DOJ", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_ID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_MAILID",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_NAME",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_PHONENO",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="employeedetails",
            name="EMP_ROLE_NAME",
            field=models.CharField(max_length=100),
        ),
    ]
