# Generated by Django 4.2.11 on 2024-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0006_employeedetails_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitordetails", name="VS_DATE", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_ID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_MAILID",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_NAME",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_PHONENO",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_PURPOSE",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_REMARKS",
            field=models.CharField(max_length=255),
        ),
    ]
