# Generated by Django 4.2.11 on 2024-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0007_alter_visitordetails_vs_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="visitordetails", name="status",),
        migrations.AddField(
            model_name="visitordetails",
            name="APPROVED",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_ID",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_MAILID",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_NAME",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_PHONENO",
            field=models.CharField(max_length=15),
        ),
    ]
