# Generated by Django 4.2.11 on 2024-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "basics",
            "0008_remove_visitordetails_status_visitordetails_approved_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="visitordetails", name="APPROVED",),
        migrations.AddField(
            model_name="visitordetails",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_ID",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_MAILID",
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_NAME",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_PHONENO",
            field=models.CharField(max_length=20),
        ),
    ]
