# Generated by Django 4.2.11 on 2024-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "basics",
            "0009_remove_visitordetails_approved_visitordetails_status_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VS_ID", models.CharField(max_length=100)),
                ("VS_NAME", models.CharField(max_length=255)),
                ("VS_DATE", models.DateField()),
                ("VS_PHONENO", models.CharField(max_length=20)),
                ("VS_MAILID", models.EmailField(max_length=255)),
                ("VS_PURPOSE", models.CharField(max_length=255)),
                ("VS_REMARKS", models.CharField(max_length=255)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
    ]
