# Generated by Django 4.2.11 on 2024-06-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0010_visitorrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorrequest",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
