# Generated by Django 4.2.11 on 2024-06-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0011_visitorrequest_approved"),
    ]

    operations = [
        migrations.RemoveField(model_name="visitorrequest", name="approved",),
        migrations.AddField(
            model_name="visitorrequest",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
