# Generated by Django 4.2.11 on 2024-06-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "basics",
            "0012_remove_visitorrequest_approved_visitorrequest_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="visitorrequest", name="status",),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_ID",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_MAILID",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_NAME",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="VS_PHONENO",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="visitordetails", name="VS_REMARKS", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="visitordetails",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="visitorrequest",
            name="VS_ID",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="visitorrequest",
            name="VS_MAILID",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="visitorrequest",
            name="VS_NAME",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="visitorrequest",
            name="VS_PHONENO",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="visitorrequest", name="VS_REMARKS", field=models.TextField(),
        ),
    ]
